apiVersion: v1
kind: Service
metadata:
  name: mysql-service-testing
  labels:
    app: mysql
    env: testing
spec:
  selector:
    app: mysql
    env: testing
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
